<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <PackageId>PK.CleanArchitecture.Identity</PackageId>
        <Version>1.0.1</Version>
        <Authors>Paavo Karppinen</Authors>
        <Description>Clean Architecture with Identity template</Description>
        <PackageType>Template</PackageType>
        <NoBuild>true</NoBuild>
        <IncludeBuildOutput>false</IncludeBuildOutput>
    </PropertyGroup>

    <ItemGroup>
        <!-- Put src at package root -->
        <Content Include="src\**\*" Exclude="src\**\bin\**;src\**\obj\**" Pack="true" PackagePath="src" />
        <!-- Put template config at package root -->
        <Content Include=".template.config\**\*" Pack="true" PackagePath=".template.config" />
    </ItemGroup>
</Project>